package com.cdm.patient.service;

import com.cdm.common.security.IdentityPayload;
import com.cdm.patient.entity.HealthMetricEntity;
import com.cdm.patient.repository.HealthMetricRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class HealthMetricService {
    private final HealthMetricRepository repository;

    public HealthMetricService(HealthMetricRepository repository) {
        this.repository = repository;
    }

    public List<HealthMetricEntity> findAllForPatient(IdentityPayload identity, Long patientId) {
        return repository.findAllByContextAndPatient(identity.getTenantId(), identity.getAllowedOrgIds(), patientId);
    }

    public HealthMetricEntity create(IdentityPayload identity, Long patientId, String metricType, String metricValue) {
        HealthMetricEntity entity = new HealthMetricEntity();
        // ID generated by common-lib snowflake
        entity.setId(com.cdm.common.util.SnowflakeIdGenerator.nextId()); 
        entity.setTenantId(identity.getTenantId());
        entity.setOrgId(identity.getOrgId());
        entity.setPatientId(patientId);
        entity.setMetricType(metricType);
        entity.setMetricValue(metricValue);
        entity.setRecordedAt(LocalDateTime.now());
        
        return repository.save(entity);
    }
}
