"""upgrade_rbac_multi_role_and_soft_delete

Revision ID: 12c3eabda525
Revises: fea8edf9ac3d
Create Date: 2026-03-21 00:17:20.035573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c3eabda525'
down_revision: Union[str, Sequence[str], None] = 'fea8edf9ac3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_user_roles',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id', 'user_id'], ['organization_users.org_id', 'organization_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id', 'role_id')
    )

    op.execute(
        """
        INSERT INTO organization_user_roles (org_id, user_id, role_id)
        SELECT org_id, user_id, role_id FROM organization_users
        WHERE role_id IS NOT NULL
        """
    )

    op.add_column('api_keys', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_api_keys_org_id_id'), table_name='api_keys')
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('chunks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_chunks_org_id_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_org_id_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_org_id_kb_id'), table_name='chunks')
    op.create_index('idx_org_kb_chunk', 'chunks', ['org_id', 'kb_id'], unique=False)
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_conversations_org_id_id'), table_name='conversations')
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_documents_org_id_id'), table_name='documents')
    op.add_column('knowledge_bases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_knowledge_bases_org_id_id'), table_name='knowledge_bases')
    op.add_column('management_suggestions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_management_suggestions_org_id_id'), table_name='management_suggestions')
    op.create_index('idx_org_patient_suggest', 'management_suggestions', ['org_id', 'patient_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('management_suggestions_manager_id_fkey'), 'management_suggestions', type_='foreignkey')
    op.drop_constraint(op.f('management_suggestions_patient_id_fkey'), 'management_suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'management_suggestions', 'patient_profiles', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'management_suggestions', 'users', ['manager_id'], ['id'])
    op.add_column('manager_profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_manager_profiles_org_id_id'), table_name='manager_profiles')
    op.drop_constraint(op.f('manager_profiles_user_id_fkey'), 'manager_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'manager_profiles', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('organization_invitations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_organization_invitations_org_id_id'), table_name='organization_invitations')
    op.add_column('organization_users', sa.Column('user_type', sa.String(length=20), server_default='staff', nullable=False))
    op.add_column('organization_users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_organization_users_role_id'), table_name='organization_users')
    op.drop_constraint(op.f('organization_users_role_id_fkey'), 'organization_users', type_='foreignkey')
    op.drop_column('organization_users', 'role')
    op.drop_column('organization_users', 'role_id')
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('patient_family_links', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('patient_manager_assignments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_patient_manager_assignments_org_id_composite'), table_name='patient_manager_assignments')
    op.drop_constraint(op.f('patient_manager_assignments_manager_id_fkey'), 'patient_manager_assignments', type_='foreignkey')
    op.drop_constraint(op.f('patient_manager_assignments_patient_id_fkey'), 'patient_manager_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'patient_manager_assignments', 'patient_profiles', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'patient_manager_assignments', 'users', ['manager_id'], ['id'])
    op.add_column('patient_profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_patient_profiles_org_id_id'), table_name='patient_profiles')
    op.create_index('idx_patient_medical_history_gin', 'patient_profiles', ['medical_history'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'])
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('usage_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_usage_logs_org_id_id'), table_name='usage_logs')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.create_index(op.f('ix_usage_logs_org_id_id'), 'usage_logs', ['org_id', 'id'], unique=False)
    op.drop_column('usage_logs', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_patient_medical_history_gin', table_name='patient_profiles', postgresql_using='gin')
    op.create_index(op.f('ix_patient_profiles_org_id_id'), 'patient_profiles', ['org_id', 'id'], unique=False)
    op.drop_column('patient_profiles', 'deleted_at')
    op.drop_constraint(None, 'patient_manager_assignments', type_='foreignkey')
    op.drop_constraint(None, 'patient_manager_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('patient_manager_assignments_patient_id_fkey'), 'patient_manager_assignments', 'patient_profiles', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('patient_manager_assignments_manager_id_fkey'), 'patient_manager_assignments', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_patient_manager_assignments_org_id_composite'), 'patient_manager_assignments', ['org_id', 'manager_id', 'patient_id'], unique=False)
    op.drop_column('patient_manager_assignments', 'deleted_at')
    op.drop_column('patient_family_links', 'deleted_at')
    op.drop_column('organizations', 'deleted_at')
    op.add_column('organization_users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))

    op.execute(
        """
        UPDATE organization_users ou
        SET role_id = subquery.role_id
        FROM (
            SELECT org_id, user_id, role_id
            FROM (
                SELECT org_id, user_id, role_id,
                       ROW_NUMBER() OVER(PARTITION BY org_id, user_id ORDER BY created_at) as rn
                FROM organization_user_roles
            ) t WHERE rn = 1
        ) subquery
        WHERE ou.org_id = subquery.org_id AND ou.user_id = subquery.user_id
        """
    )

    op.add_column('organization_users', sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('organization_users_role_id_fkey'), 'organization_users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_organization_users_role_id'), 'organization_users', ['role_id'], unique=False)
    op.drop_column('organization_users', 'deleted_at')
    op.drop_column('organization_users', 'user_type')
    op.create_index(op.f('ix_organization_invitations_org_id_id'), 'organization_invitations', ['org_id', 'id'], unique=False)
    op.drop_column('organization_invitations', 'deleted_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_constraint(None, 'manager_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('manager_profiles_user_id_fkey'), 'manager_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_manager_profiles_org_id_id'), 'manager_profiles', ['org_id', 'id'], unique=False)
    op.drop_column('manager_profiles', 'deleted_at')
    op.drop_constraint(None, 'management_suggestions', type_='foreignkey')
    op.drop_constraint(None, 'management_suggestions', type_='foreignkey')
    op.create_foreign_key(op.f('management_suggestions_patient_id_fkey'), 'management_suggestions', 'patient_profiles', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('management_suggestions_manager_id_fkey'), 'management_suggestions', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_org_patient_suggest', table_name='management_suggestions')
    op.create_index(op.f('ix_management_suggestions_org_id_id'), 'management_suggestions', ['org_id', 'id'], unique=False)
    op.drop_column('management_suggestions', 'deleted_at')
    op.create_index(op.f('ix_knowledge_bases_org_id_id'), 'knowledge_bases', ['org_id', 'id'], unique=False)
    op.drop_column('knowledge_bases', 'deleted_at')
    op.create_index(op.f('ix_documents_org_id_id'), 'documents', ['org_id', 'id'], unique=False)
    op.drop_column('documents', 'deleted_at')
    op.create_index(op.f('ix_conversations_org_id_id'), 'conversations', ['org_id', 'id'], unique=False)
    op.drop_column('conversations', 'deleted_at')
    op.drop_index('idx_org_kb_chunk', table_name='chunks')
    op.create_index(op.f('ix_chunks_org_id_kb_id'), 'chunks', ['org_id', 'kb_id'], unique=False)
    op.create_index(op.f('ix_chunks_org_id_id'), 'chunks', ['org_id', 'id'], unique=False)
    op.create_index(op.f('ix_chunks_org_id_document_id'), 'chunks', ['org_id', 'document_id'], unique=False)
    op.drop_column('chunks', 'deleted_at')
    op.drop_column('audit_logs', 'deleted_at')
    op.create_index(op.f('ix_api_keys_org_id_id'), 'api_keys', ['org_id', 'id'], unique=False)
    op.drop_column('api_keys', 'deleted_at')
    op.drop_table('organization_user_roles')
    # ### end Alembic commands ###
