"""add_management_suggestions

Revision ID: 4c7042fd1801
Revises: f4f01459e3d7
Create Date: 2026-03-16 22:57:11.016252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7042fd1801'
down_revision: Union[str, Sequence[str], None] = 'f4f01459e3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_suggestions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_suggestions_manager_id'), 'management_suggestions', ['manager_id'], unique=False)
    op.create_index(op.f('ix_management_suggestions_org_id'), 'management_suggestions', ['org_id'], unique=False)
    op.create_index(op.f('ix_management_suggestions_patient_id'), 'management_suggestions', ['patient_id'], unique=False)
    
    # Enable RLS
    op.execute("ALTER TABLE management_suggestions ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY management_suggestions_isolation_policy ON management_suggestions "
        "USING (org_id = current_setting('app.current_org_id', true)::UUID)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS management_suggestions_isolation_policy ON management_suggestions")
    op.execute("ALTER TABLE management_suggestions DISABLE ROW LEVEL SECURITY")

    op.drop_index(op.f('ix_management_suggestions_patient_id'), table_name='management_suggestions')
    op.drop_index(op.f('ix_management_suggestions_org_id'), table_name='management_suggestions')
    op.drop_index(op.f('ix_management_suggestions_manager_id'), table_name='management_suggestions')
    op.drop_table('management_suggestions')
    # ### end Alembic commands ###
