"""upgrade_rbac_to_standard_v3

Revision ID: 50de6f1ad6be
Revises: 9a92f65eca42
Create Date: 2026-03-31 21:47:56.454282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50de6f1ad6be'
down_revision: Union[str, Sequence[str], None] = '9a92f65eca42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up old data before significant structural changes to ensure migration success
    op.execute("DELETE FROM role_permissions")
    op.execute("DELETE FROM permissions")

    op.create_table('rbac_actions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_actions_code'), 'rbac_actions', ['code'], unique=True)
    op.create_index(op.f('ix_rbac_actions_name'), 'rbac_actions', ['name'], unique=True)
    op.create_table('rbac_resources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_resources_code'), 'rbac_resources', ['code'], unique=True)
    op.create_index(op.f('ix_rbac_resources_name'), 'rbac_resources', ['name'], unique=True)
    op.create_table('rbac_role_constraints',
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('constraint_type', sa.String(length=20), nullable=False),
    sa.Column('role_id_1', sa.BigInteger(), nullable=False),
    sa.Column('role_id_2', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id_1'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id_2'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id_1', 'role_id_2', 'constraint_type', name='_role_conflict_uc')
    )
    op.create_index(op.f('ix_rbac_role_constraints_org_id'), 'rbac_role_constraints', ['org_id'], unique=False)
    op.add_column('permissions', sa.Column('resource_id', sa.BigInteger(), nullable=False))
    op.add_column('permissions', sa.Column('action_id', sa.BigInteger(), nullable=False))
    op.add_column('permissions', sa.Column('permission_type', sa.String(length=20), server_default='api', nullable=False))
    op.add_column('permissions', sa.Column('ui_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_unique_constraint('_resource_action_uc', 'permissions', ['resource_id', 'action_id'])
    op.create_index(op.f('ix_permissions_action_id'), 'permissions', ['action_id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_id'), 'permissions', ['resource_id'], unique=False)
    op.create_foreign_key(None, 'permissions', 'rbac_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'rbac_resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.drop_column('permissions', 'description')
    op.add_column('roles', sa.Column('parent_role_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_roles_parent_role_id'), 'roles', ['parent_role_id'], unique=False)
    op.create_foreign_key(None, 'roles', 'roles', ['parent_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_parent_role_id'), table_name='roles')
    op.drop_column('roles', 'parent_role_id')
    op.add_column('permissions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_index(op.f('ix_permissions_resource_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action_id'), table_name='permissions')
    op.drop_constraint('_resource_action_uc', 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_column('permissions', 'ui_metadata')
    op.drop_column('permissions', 'permission_type')
    op.drop_column('permissions', 'action_id')
    op.drop_column('permissions', 'resource_id')
    op.drop_index(op.f('ix_rbac_role_constraints_org_id'), table_name='rbac_role_constraints')
    op.drop_table('rbac_role_constraints')
    op.drop_index(op.f('ix_rbac_resources_name'), table_name='rbac_resources')
    op.drop_index(op.f('ix_rbac_resources_code'), table_name='rbac_resources')
    op.drop_table('rbac_resources')
    op.drop_index(op.f('ix_rbac_actions_name'), table_name='rbac_actions')
    op.drop_index(op.f('ix_rbac_actions_code'), table_name='rbac_actions')
    op.drop_table('rbac_actions')
    # ### end Alembic commands ###
