"""add_system_settings_table

Revision ID: 9a92f65eca42
Revises: a6ac5d955734
Create Date: 2026-03-29 02:30:20.493041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a92f65eca42'
down_revision: Union[str, Sequence[str], None] = 'a6ac5d955734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    # ### end Alembic commands ###

    # Insert initial settings
    op.execute(
        "INSERT INTO system_settings (key, value, description) VALUES "
        "('llm_default_model', 'gpt-4o-mini', 'Default model for chat'), "
        "('rag_max_chunks', '5', 'Default max chunks for retrieval'), "
        "('system_maintenance_mode', 'false', 'Enable/disable system maintenance mode')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
