// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/codes/chronic-disease-management/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.3_792b4c4e81f02f76b4abcb63412c03a7/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
